project:
  type: website
  output-dir: docs
  render:
    - index.qmd
    - blog/index.qmd
    - blog/posts/**/*.qmd
  resources:
    - CNAME
    - .nojekyll
    - robots.txt

website:
  title: "Joshua Kunst"
  site-url: "https://jkunst.com"
  google-analytics: "G-ECZ9XLT78C"
  draft-mode: unlinked
  search: false
  navbar:
    title: "jk"
    pinned: true
    right:
      - text: Blog
        href: blog/index.qmd
      - text: Visual Data Lab ↗
        href: https://jkunst.com/visual-data-lab/
      - text: Visual Data Sketches ↗
        href: https://jkunst.com/visual-data-sketches/
      - text: GitHub ↗
        href: https://github.com/jbkunst
  page-footer:
    center: "Joshua Kunst · 2026 · Built with [Quarto](https://quarto.org/)"

execute:
  freeze: auto

format:
  html:
    theme: none
    css: assets/css/navbar.css
    minimal: true
