project:
  type: website
  output-dir: docs
  render:
    - index.qmd
    - blog/index.qmd
    - blog/posts/**/*.qmd
  resources:
    - CNAME
    - .nojekyll

website:
  title: "Joshua Kunst"
  site-url: https://jbkunst.github.io
  search: false
  navbar:
    title: "jk"
    pinned: true
    right:
      - text: Blog
        href: blog/index.qmd
      - text: Visual Data Lab ↗
        href: https://jbkunst.com/visual-data-lab/
      - text: GitHub ↗
        href: https://github.com/jbkunst

execute:
  freeze: auto

format:
  html:
    theme: none
    css: assets/css/navbar.css
    minimal: true
